name: Build and Publish
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: bash build.sh

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          build/*
    - name: Publish as tag 'latest'
      uses: softprops/action-gh-release@v1
      with:
        name: 'latest'
        tag_name: 'latest'
        draft: false
        prerelease: false
        files: |
          build/*